{{- if (not .Values.general.deployAsDaemonSet) -}}
{{- if .Values.blueDeployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "password-generator.name" . }}-blue
  namespace: {{ include "password-generator.namespace" . }}
  labels:
    {{- include "password-generator.full_labels" . | nindent 4 }}
    {{- with .Values.blueDeployment.labels -}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    color: blue
  annotations:
    {{- include "password-generator.full_annotations" . | nindent 4 }}
    {{- with .Values.blueDeployment.annotations -}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.blueDeployment }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "password-generator.full_labels" $ | nindent 6 -}}
      {{- with .labels -}}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      color: blue
  template:
    metadata:
      labels:
        {{- include "password-generator.full_labels" $ | nindent 8 }}
        {{- with .labels -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        color: blue
      annotations:
        {{- include "password-generator.full_annotations" $ | nindent 8 }}
        {{- with .annotations -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- include "password-generator.pod_spec" . | nindent 4 }}
{{- end -}}
{{- end }}

{{- if .Values.greenDeployment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "password-generator.name" . }}-green
  namespace: {{ include "password-generator.namespace" . }}
  labels:
    {{- include "password-generator.full_labels" . | nindent 4 }}
    {{- with .Values.greenDeployment.labels -}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    color: green
  annotations:
    {{- include "password-generator.full_annotations" . | nindent 4 }}
    {{- with .Values.greenDeployment.annotations -}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.greenDeployment }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "password-generator.full_labels" $ | nindent 6 -}}
      {{- with .labels -}}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      color: green
  template:
    metadata:
      labels:
        {{- include "password-generator.full_labels" $ | nindent 8 }}
        {{- with .labels -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        color: green
      annotations:
        {{- include "password-generator.full_annotations" $ | nindent 8 }}
        {{- with .annotations -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- include "password-generator.pod_spec" . | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}